name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.4.2
  lottie: ^2.7.0
  video_player: ^2.7.0
  image_picker: ^1.1.2
  intl: ^0.18.1  # Tambahkan ini untuk date formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/illustration1.png
    - assets/illustration2.png
    - assets/illustration3.png
    - assets/profile.png
    - assets/LaporPak.mp4
    - assets/jalan_lubang.png
    - assets/lampu_mati.png
    - assets/lampu_selesai.png